// magicCreateTable.idl : magicCreateTable 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(magicCreateTable.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(4C0D1713-69AC-4D74-8859-A611EECC84EC),
	version(1.0),
	helpstring("magicCreateTable 1.0 类型库")
]
library magicCreateTableLib
{
	importlib("stdole2.tlb");
};
