// magicRegisterServer.idl : magicRegisterServer 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(magicRegisterServer.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(D2DFAFEC-F03B-464D-B5AE-50511AA6E768),
	version(1.0),
	helpstring("magicRegisterServer 1.0 类型库")
]
library magicRegisterServerLib
{
	importlib("stdole2.tlb");
};
